<?xml version="1.0"?>
<package format="3">
  <name>maker_basic</name>
  <version>0.1.0</version>
  <description>ROS2 maker guide book examples</description>
  <maintainer email="freshmea@naver.com">choi su gil</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>user_interface</exec_depend>
  <exec_depend>rcl_interfaces</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>ros2launch</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
